-- Module GMAO : équipements, interventions, plans préventifs
CREATE TABLE IF NOT EXISTS gmao_equipement (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  code_interne VARCHAR(64) NOT NULL,
  designation VARCHAR(255) NOT NULL,
  categorie VARCHAR(40) NOT NULL DEFAULT 'AUTRE',
  marque VARCHAR(120) NULL,
  modele VARCHAR(120) NULL,
  numero_serie VARCHAR(120) NULL,
  fk_site BIGINT NULL,
  fk_pharmacie BIGINT NULL,
  localisation VARCHAR(255) NULL,
  statut VARCHAR(40) NOT NULL DEFAULT 'EN_SERVICE',
  criticite VARCHAR(20) NOT NULL DEFAULT 'MOYENNE',
  date_mise_en_service DATE NULL,
  date_garantie_fin DATE NULL,
  date_inventaire DATE NULL,
  nom_inventoriste VARCHAR(160) NULL,
  etablissement VARCHAR(160) NULL,
  service VARCHAR(160) NULL,
  fabricant VARCHAR(120) NULL,
  pays_acquisition VARCHAR(80) NULL,
  annee_fabrication SMALLINT NULL,
  date_installation DATE NULL,
  fournisseur VARCHAR(160) NULL,
  fournisseur_correspondant VARCHAR(160) NULL,
  fournisseur_telephone VARCHAR(60) NULL,
  fournisseur_email VARCHAR(120) NULL,
  fournisseur_adresse TEXT NULL,
  etat_general VARCHAR(30) NULL,
  fonctionnement VARCHAR(40) NULL,
  contrat_maintenance TINYINT(1) NOT NULL DEFAULT 0,
  contrat_numero VARCHAR(80) NULL,
  contrat_echeance DATE NULL,
  maintenance_interne TINYINT(1) NOT NULL DEFAULT 0,
  maintenance_externe TINYINT(1) NOT NULL DEFAULT 0,
  frequence_maintenance_jours INT NULL,
  derniere_maintenance DATE NULL,
  prochaine_maintenance DATE NULL,
  technicien_responsable VARCHAR(160) NULL,
  technicien_contact VARCHAR(160) NULL,
  consommables_disponibles TINYINT(1) NOT NULL DEFAULT 0,
  pieces_rechange_disponibles TINYINT(1) NOT NULL DEFAULT 0,
  manuel_utilisateur TINYINT(1) NOT NULL DEFAULT 0,
  manuel_technique TINYINT(1) NOT NULL DEFAULT 0,
  accessoires_complets TINYINT(1) NOT NULL DEFAULT 0,
  responsable_service VARCHAR(160) NULL,
  ingenieur_biomedical VARCHAR(160) NULL,
  notes TEXT NULL,
  actif TINYINT(1) NOT NULL DEFAULT 1,
  datecreate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  dateupdate TIMESTAMP NULL,
  usercreateid BIGINT NULL,
  userupdateid BIGINT NULL,
  UNIQUE KEY uk_gmao_equipement_code (code_interne),
  INDEX idx_gmao_equipement_statut (statut),
  INDEX idx_gmao_equipement_pharmacie (fk_pharmacie),
  INDEX idx_gmao_equipement_categorie (categorie)
);

CREATE TABLE IF NOT EXISTS gmao_intervention (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  numero VARCHAR(40) NOT NULL,
  fk_equipement BIGINT NOT NULL,
  type_intervention VARCHAR(30) NOT NULL DEFAULT 'CORRECTIVE',
  priorite VARCHAR(20) NOT NULL DEFAULT 'NORMALE',
  statut VARCHAR(30) NOT NULL DEFAULT 'BROUILLON',
  titre VARCHAR(255) NOT NULL,
  description TEXT NULL,
  diagnostic TEXT NULL,
  travaux_realises TEXT NULL,
  technicien_nom VARCHAR(160) NULL,
  technicien_user_id BIGINT NULL,
  fk_pharmacie BIGINT NULL,
  date_demande TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  date_planifiee TIMESTAMP NULL,
  date_debut TIMESTAMP NULL,
  date_cloture TIMESTAMP NULL,
  cout_estime DECIMAL(14,2) NULL,
  cout_reel DECIMAL(14,2) NULL,
  datecreate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  dateupdate TIMESTAMP NULL,
  usercreateid BIGINT NULL,
  userupdateid BIGINT NULL,
  UNIQUE KEY uk_gmao_intervention_numero (numero),
  INDEX idx_gmao_intervention_statut (statut),
  INDEX idx_gmao_intervention_equipement (fk_equipement),
  INDEX idx_gmao_intervention_pharmacie (fk_pharmacie),
  CONSTRAINT fk_gmao_intervention_equipement
    FOREIGN KEY (fk_equipement) REFERENCES gmao_equipement (id)
);

CREATE TABLE IF NOT EXISTS gmao_plan_preventif (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  fk_equipement BIGINT NOT NULL,
  libelle VARCHAR(255) NOT NULL,
  frequence_jours INT NOT NULL DEFAULT 90,
  prochaine_echeance DATE NOT NULL,
  derniere_execution DATE NULL,
  actif TINYINT(1) NOT NULL DEFAULT 1,
  notes TEXT NULL,
  datecreate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  dateupdate TIMESTAMP NULL,
  usercreateid BIGINT NULL,
  userupdateid BIGINT NULL,
  INDEX idx_gmao_plan_echeance (prochaine_echeance, actif),
  INDEX idx_gmao_plan_equipement (fk_equipement),
  CONSTRAINT fk_gmao_plan_equipement
    FOREIGN KEY (fk_equipement) REFERENCES gmao_equipement (id)
);

CREATE TABLE IF NOT EXISTS gmao_equipement_media (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  fk_equipement BIGINT NOT NULL,
  type_media VARCHAR(30) NOT NULL DEFAULT 'PHOTO',
  nom_fichier VARCHAR(255) NOT NULL,
  nom_original VARCHAR(255) NOT NULL,
  content_type VARCHAR(120) NOT NULL,
  taille_octets BIGINT NOT NULL DEFAULT 0,
  storage_key VARCHAR(500) NOT NULL,
  legende VARCHAR(255) NULL,
  est_principal TINYINT(1) NOT NULL DEFAULT 0,
  datecreate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  usercreateid BIGINT NULL,
  INDEX idx_gmao_media_equipement (fk_equipement),
  INDEX idx_gmao_media_principal (fk_equipement, est_principal),
  CONSTRAINT fk_gmao_media_equipement
    FOREIGN KEY (fk_equipement) REFERENCES gmao_equipement (id)
);

-- Campagne d'inventaire physique (vérification de disponibilité) — distinct de l'identification
CREATE TABLE IF NOT EXISTS gmao_inventaire_campagne (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  numero VARCHAR(40) NOT NULL,
  libelle VARCHAR(255) NOT NULL,
  date_debut DATE NOT NULL,
  date_fin_prevue DATE NULL,
  date_cloture TIMESTAMP NULL,
  statut VARCHAR(30) NOT NULL DEFAULT 'BROUILLON',
  perimetre_service VARCHAR(160) NULL,
  perimetre_categorie VARCHAR(40) NULL,
  responsable VARCHAR(160) NULL,
  notes TEXT NULL,
  datecreate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  dateupdate TIMESTAMP NULL,
  usercreateid BIGINT NULL,
  userupdateid BIGINT NULL,
  UNIQUE KEY uk_gmao_inv_campagne_numero (numero),
  INDEX idx_gmao_inv_campagne_statut (statut)
);

CREATE TABLE IF NOT EXISTS gmao_inventaire_ligne (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  fk_campagne BIGINT NOT NULL,
  fk_equipement BIGINT NOT NULL,
  resultat VARCHAR(30) NOT NULL DEFAULT 'A_VERIFIER',
  localisation_systeme VARCHAR(255) NULL,
  localisation_constatee VARCHAR(255) NULL,
  etat_constate VARCHAR(30) NULL,
  fonctionnement_constate VARCHAR(40) NULL,
  consommables_ok TINYINT(1) NULL,
  pieces_ok TINYINT(1) NULL,
  manuel_utilisateur_ok TINYINT(1) NULL,
  manuel_technique_ok TINYINT(1) NULL,
  accessoires_ok TINYINT(1) NULL,
  remarque TEXT NULL,
  inventoriste VARCHAR(160) NULL,
  date_controle TIMESTAMP NULL,
  ecart TINYINT(1) NOT NULL DEFAULT 0,
  datecreate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  dateupdate TIMESTAMP NULL,
  usercreateid BIGINT NULL,
  userupdateid BIGINT NULL,
  UNIQUE KEY uk_gmao_inv_ligne (fk_campagne, fk_equipement),
  INDEX idx_gmao_inv_ligne_campagne (fk_campagne),
  INDEX idx_gmao_inv_ligne_resultat (resultat),
  CONSTRAINT fk_gmao_inv_ligne_campagne
    FOREIGN KEY (fk_campagne) REFERENCES gmao_inventaire_campagne (id),
  CONSTRAINT fk_gmao_inv_ligne_equipement
    FOREIGN KEY (fk_equipement) REFERENCES gmao_equipement (id)
);
