-- Extension fiche d'identification DM CMK (idempotent via GmaoSchemaInitializer)
ALTER TABLE gmao_equipement ADD COLUMN date_inventaire DATE NULL;
ALTER TABLE gmao_equipement ADD COLUMN nom_inventoriste VARCHAR(160) NULL;
ALTER TABLE gmao_equipement ADD COLUMN etablissement VARCHAR(160) NULL;
ALTER TABLE gmao_equipement ADD COLUMN service VARCHAR(160) NULL;
ALTER TABLE gmao_equipement ADD COLUMN fabricant VARCHAR(120) NULL;
ALTER TABLE gmao_equipement ADD COLUMN pays_acquisition VARCHAR(80) NULL;
ALTER TABLE gmao_equipement ADD COLUMN annee_fabrication SMALLINT NULL;
ALTER TABLE gmao_equipement ADD COLUMN date_installation DATE NULL;
ALTER TABLE gmao_equipement ADD COLUMN fournisseur VARCHAR(160) NULL;
ALTER TABLE gmao_equipement ADD COLUMN fournisseur_correspondant VARCHAR(160) NULL;
ALTER TABLE gmao_equipement ADD COLUMN fournisseur_telephone VARCHAR(60) NULL;
ALTER TABLE gmao_equipement ADD COLUMN fournisseur_email VARCHAR(120) NULL;
ALTER TABLE gmao_equipement ADD COLUMN fournisseur_adresse TEXT NULL;
ALTER TABLE gmao_equipement ADD COLUMN etat_general VARCHAR(30) NULL;
ALTER TABLE gmao_equipement ADD COLUMN fonctionnement VARCHAR(40) NULL;
ALTER TABLE gmao_equipement ADD COLUMN contrat_maintenance TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE gmao_equipement ADD COLUMN contrat_numero VARCHAR(80) NULL;
ALTER TABLE gmao_equipement ADD COLUMN contrat_echeance DATE NULL;
ALTER TABLE gmao_equipement ADD COLUMN maintenance_interne TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE gmao_equipement ADD COLUMN maintenance_externe TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE gmao_equipement ADD COLUMN frequence_maintenance_jours INT NULL;
ALTER TABLE gmao_equipement ADD COLUMN derniere_maintenance DATE NULL;
ALTER TABLE gmao_equipement ADD COLUMN prochaine_maintenance DATE NULL;
ALTER TABLE gmao_equipement ADD COLUMN technicien_responsable VARCHAR(160) NULL;
ALTER TABLE gmao_equipement ADD COLUMN technicien_contact VARCHAR(160) NULL;
ALTER TABLE gmao_equipement ADD COLUMN consommables_disponibles TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE gmao_equipement ADD COLUMN pieces_rechange_disponibles TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE gmao_equipement ADD COLUMN manuel_utilisateur TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE gmao_equipement ADD COLUMN manuel_technique TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE gmao_equipement ADD COLUMN accessoires_complets TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE gmao_equipement ADD COLUMN responsable_service VARCHAR(160) NULL;
ALTER TABLE gmao_equipement ADD COLUMN ingenieur_biomedical VARCHAR(160) NULL;
